/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.google.firebase.database;

public final class R {
    public static final class attr {
        public static final int buttonSize = 0x7f03004d;
        public static final int circleCrop = 0x7f030066;
        public static final int colorScheme = 0x7f030076;
        public static final int font = 0x7f0300ad;
        public static final int fontProviderAuthority = 0x7f0300af;
        public static final int fontProviderCerts = 0x7f0300b0;
        public static final int fontProviderFetchStrategy = 0x7f0300b1;
        public static final int fontProviderFetchTimeout = 0x7f0300b2;
        public static final int fontProviderPackage = 0x7f0300b3;
        public static final int fontProviderQuery = 0x7f0300b4;
        public static final int fontStyle = 0x7f0300b5;
        public static final int fontWeight = 0x7f0300b6;
        public static final int imageAspectRatio = 0x7f0300c8;
        public static final int imageAspectRatioAdjust = 0x7f0300c9;
        public static final int scopeUris = 0x7f030170;
    }
    public static final class bool {
        public static final int abc_action_bar_embed_tabs = 0x7f040000;
    }
    public static final class color {
        public static final int common_google_signin_btn_text_dark = 0x7f050035;
        public static final int common_google_signin_btn_text_dark_default = 0x7f050036;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f050037;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f050038;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f050039;
        public static final int common_google_signin_btn_text_light = 0x7f05003a;
        public static final int common_google_signin_btn_text_light_default = 0x7f05003b;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f05003c;
        public static final int common_google_signin_btn_text_light_focused = 0x7f05003d;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f05003e;
        public static final int common_google_signin_btn_tint = 0x7f05003f;
        public static final int notification_action_color_filter = 0x7f050061;
        public static final int notification_icon_bg_color = 0x7f050062;
        public static final int notification_material_background_media_default_color = 0x7f050063;
        public static final int primary_text_default_material_dark = 0x7f05006e;
        public static final int ripple_material_light = 0x7f050074;
        public static final int secondary_text_default_material_dark = 0x7f050075;
        public static final int secondary_text_default_material_light = 0x7f050076;
    }
    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 0x7f060051;
        public static final int compat_button_inset_vertical_material = 0x7f060052;
        public static final int compat_button_padding_horizontal_material = 0x7f060053;
        public static final int compat_button_padding_vertical_material = 0x7f060054;
        public static final int compat_control_corner_material = 0x7f060055;
        public static final int notification_action_icon_size = 0x7f060095;
        public static final int notification_action_text_size = 0x7f060096;
        public static final int notification_big_circle_margin = 0x7f060097;
        public static final int notification_content_margin_start = 0x7f060098;
        public static final int notification_large_icon_height = 0x7f060099;
        public static final int notification_large_icon_width = 0x7f06009a;
        public static final int notification_main_column_padding_top = 0x7f06009b;
        public static final int notification_media_narrow_margin = 0x7f06009c;
        public static final int notification_right_icon_size = 0x7f06009d;
        public static final int notification_right_side_padding_top = 0x7f06009e;
        public static final int notification_small_icon_background_padding = 0x7f06009f;
        public static final int notification_small_icon_size_as_large = 0x7f0600a0;
        public static final int notification_subtext_size = 0x7f0600a1;
        public static final int notification_top_pad = 0x7f0600a2;
        public static final int notification_top_pad_large_text = 0x7f0600a3;
    }
    public static final class drawable {
        public static final int common_full_open_on_phone = 0x7f070060;
        public static final int common_google_signin_btn_icon_dark = 0x7f070061;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f070062;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f070063;
        public static final int common_google_signin_btn_icon_dark_normal_background = 0x7f070064;
        public static final int common_google_signin_btn_icon_disabled = 0x7f070065;
        public static final int common_google_signin_btn_icon_light = 0x7f070066;
        public static final int common_google_signin_btn_icon_light_focused = 0x7f070067;
        public static final int common_google_signin_btn_icon_light_normal = 0x7f070068;
        public static final int common_google_signin_btn_icon_light_normal_background = 0x7f070069;
        public static final int common_google_signin_btn_text_dark = 0x7f07006a;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f07006b;
        public static final int common_google_signin_btn_text_dark_normal = 0x7f07006c;
        public static final int common_google_signin_btn_text_dark_normal_background = 0x7f07006d;
        public static final int common_google_signin_btn_text_disabled = 0x7f07006e;
        public static final int common_google_signin_btn_text_light = 0x7f07006f;
        public static final int common_google_signin_btn_text_light_focused = 0x7f070070;
        public static final int common_google_signin_btn_text_light_normal = 0x7f070071;
        public static final int common_google_signin_btn_text_light_normal_background = 0x7f070072;
        public static final int googleg_disabled_color_18 = 0x7f07007a;
        public static final int googleg_standard_color_18 = 0x7f07007b;
        public static final int notification_action_background = 0x7f070083;
        public static final int notification_bg = 0x7f070084;
        public static final int notification_bg_low = 0x7f070085;
        public static final int notification_bg_low_normal = 0x7f070086;
        public static final int notification_bg_low_pressed = 0x7f070087;
        public static final int notification_bg_normal = 0x7f070088;
        public static final int notification_bg_normal_pressed = 0x7f070089;
        public static final int notification_icon_background = 0x7f07008a;
        public static final int notification_template_icon_bg = 0x7f07008b;
        public static final int notification_template_icon_low_bg = 0x7f07008c;
        public static final int notification_tile_bg = 0x7f07008d;
        public static final int notify_panel_notification_icon_bg = 0x7f07008e;
    }
    public static final class id {
        public static final int action0 = 0x7f080000;
        public static final int action_container = 0x7f080008;
        public static final int action_divider = 0x7f08000a;
        public static final int action_image = 0x7f08000b;
        public static final int action_text = 0x7f080011;
        public static final int actions = 0x7f080012;
        public static final int adjust_height = 0x7f080015;
        public static final int adjust_width = 0x7f080016;
        public static final int async = 0x7f08001e;
        public static final int auto = 0x7f08001f;
        public static final int blocking = 0x7f080022;
        public static final int cancel_action = 0x7f08002f;
        public static final int chronometer = 0x7f080035;
        public static final int dark = 0x7f08003d;
        public static final int end_padder = 0x7f080053;
        public static final int forever = 0x7f08005d;
        public static final int icon = 0x7f08006b;
        public static final int icon_group = 0x7f08006c;
        public static final int icon_only = 0x7f08006d;
        public static final int info = 0x7f080070;
        public static final int italic = 0x7f080072;
        public static final int light = 0x7f080077;
        public static final int line1 = 0x7f080078;
        public static final int line3 = 0x7f080079;
        public static final int media_actions = 0x7f080082;
        public static final int none = 0x7f080089;
        public static final int normal = 0x7f08008a;
        public static final int notification_background = 0x7f08008b;
        public static final int notification_main_column = 0x7f08008c;
        public static final int notification_main_column_container = 0x7f08008d;
        public static final int right_icon = 0x7f0800a3;
        public static final int right_side = 0x7f0800a4;
        public static final int standard = 0x7f0800ca;
        public static final int status_bar_latest_event_content = 0x7f0800cc;
        public static final int text = 0x7f0800d3;
        public static final int text2 = 0x7f0800d4;
        public static final int time = 0x7f0800da;
        public static final int title = 0x7f0800db;
        public static final int wide = 0x7f0800e8;
    }
    public static final class integer {
        public static final int cancel_button_image_alpha = 0x7f090007;
        public static final int google_play_services_version = 0x7f09000a;
        public static final int status_bar_notification_info_maxnum = 0x7f09000d;
    }
    public static final class layout {
        public static final int notification_action = 0x7f0a002e;
        public static final int notification_action_tombstone = 0x7f0a002f;
        public static final int notification_media_action = 0x7f0a0030;
        public static final int notification_media_cancel_action = 0x7f0a0031;
        public static final int notification_template_big_media = 0x7f0a0032;
        public static final int notification_template_big_media_custom = 0x7f0a0033;
        public static final int notification_template_big_media_narrow = 0x7f0a0034;
        public static final int notification_template_big_media_narrow_custom = 0x7f0a0035;
        public static final int notification_template_custom_big = 0x7f0a0036;
        public static final int notification_template_icon_group = 0x7f0a0037;
        public static final int notification_template_lines_media = 0x7f0a0038;
        public static final int notification_template_media = 0x7f0a0039;
        public static final int notification_template_media_custom = 0x7f0a003a;
        public static final int notification_template_part_chronometer = 0x7f0a003b;
        public static final int notification_template_part_time = 0x7f0a003c;
    }
    public static final class string {
        public static final int common_google_play_services_enable_button = 0x7f0c0023;
        public static final int common_google_play_services_enable_text = 0x7f0c0024;
        public static final int common_google_play_services_enable_title = 0x7f0c0025;
        public static final int common_google_play_services_install_button = 0x7f0c0026;
        public static final int common_google_play_services_install_text = 0x7f0c0027;
        public static final int common_google_play_services_install_title = 0x7f0c0028;
        public static final int common_google_play_services_notification_channel_name = 0x7f0c0029;
        public static final int common_google_play_services_notification_ticker = 0x7f0c002a;
        public static final int common_google_play_services_unknown_issue = 0x7f0c002b;
        public static final int common_google_play_services_unsupported_text = 0x7f0c002c;
        public static final int common_google_play_services_update_button = 0x7f0c002d;
        public static final int common_google_play_services_update_text = 0x7f0c002e;
        public static final int common_google_play_services_update_title = 0x7f0c002f;
        public static final int common_google_play_services_updating_text = 0x7f0c0030;
        public static final int common_google_play_services_wear_update_text = 0x7f0c0031;
        public static final int common_open_on_phone = 0x7f0c0032;
        public static final int common_signin_button_text = 0x7f0c0033;
        public static final int common_signin_button_text_long = 0x7f0c0034;
        public static final int status_bar_notification_info_overflow = 0x7f0c0047;
    }
    public static final class style {
        public static final int TextAppearance_Compat_Notification = 0x7f0d00fa;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0d00fb;
        public static final int TextAppearance_Compat_Notification_Info_Media = 0x7f0d00fc;
        public static final int TextAppearance_Compat_Notification_Line2 = 0x7f0d00fd;
        public static final int TextAppearance_Compat_Notification_Line2_Media = 0x7f0d00fe;
        public static final int TextAppearance_Compat_Notification_Media = 0x7f0d00ff;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0d0100;
        public static final int TextAppearance_Compat_Notification_Time_Media = 0x7f0d0101;
        public static final int TextAppearance_Compat_Notification_Title = 0x7f0d0102;
        public static final int TextAppearance_Compat_Notification_Title_Media = 0x7f0d0103;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0d0184;
        public static final int Widget_Compat_NotificationActionText = 0x7f0d0185;
    }
    public static final class styleable {
        public static final int[] FontFamily = { 0x7f0300af, 0x7f0300b0, 0x7f0300b1, 0x7f0300b2, 0x7f0300b3, 0x7f0300b4 };
        public static final int FontFamily_fontProviderAuthority = 0;
        public static final int FontFamily_fontProviderCerts = 1;
        public static final int FontFamily_fontProviderFetchStrategy = 2;
        public static final int FontFamily_fontProviderFetchTimeout = 3;
        public static final int FontFamily_fontProviderPackage = 4;
        public static final int FontFamily_fontProviderQuery = 5;
        public static final int[] FontFamilyFont = { 0x7f0300ad, 0x7f0300b5, 0x7f0300b6 };
        public static final int FontFamilyFont_font = 0;
        public static final int FontFamilyFont_fontStyle = 1;
        public static final int FontFamilyFont_fontWeight = 2;
        public static final int[] LoadingImageView = { 0x7f030066, 0x7f0300c8, 0x7f0300c9 };
        public static final int LoadingImageView_circleCrop = 0;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 2;
        public static final int[] SignInButton = { 0x7f03004d, 0x7f030076, 0x7f030170 };
        public static final int SignInButton_buttonSize = 0;
        public static final int SignInButton_colorScheme = 1;
        public static final int SignInButton_scopeUris = 2;
    }
}
