/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.google.android.gms.wallet;

public final class R {
    public static final class attr {
        public static final int appTheme = 0x7f03002d;
        public static final int buyButtonAppearance = 0x7f030052;
        public static final int buyButtonHeight = 0x7f030053;
        public static final int buyButtonText = 0x7f030054;
        public static final int buyButtonWidth = 0x7f030055;
        public static final int customThemeStyle = 0x7f03008e;
        public static final int environment = 0x7f0300a0;
        public static final int fragmentMode = 0x7f0300b8;
        public static final int fragmentStyle = 0x7f0300b9;
        public static final int maskedWalletDetailsBackground = 0x7f030126;
        public static final int maskedWalletDetailsButtonBackground = 0x7f030127;
        public static final int maskedWalletDetailsButtonTextAppearance = 0x7f030128;
        public static final int maskedWalletDetailsHeaderTextAppearance = 0x7f030129;
        public static final int maskedWalletDetailsLogoImageType = 0x7f03012a;
        public static final int maskedWalletDetailsLogoTextColor = 0x7f03012b;
        public static final int maskedWalletDetailsTextAppearance = 0x7f03012c;
        public static final int toolbarTextColorStyle = 0x7f0301c6;
        public static final int windowTransitionStyle = 0x7f0301de;
    }
    public static final class color {
        public static final int wallet_bright_foreground_disabled_holo_light = 0x7f050080;
        public static final int wallet_bright_foreground_holo_dark = 0x7f050081;
        public static final int wallet_bright_foreground_holo_light = 0x7f050082;
        public static final int wallet_dim_foreground_disabled_holo_dark = 0x7f050083;
        public static final int wallet_dim_foreground_holo_dark = 0x7f050084;
        public static final int wallet_highlighted_text_holo_dark = 0x7f050085;
        public static final int wallet_highlighted_text_holo_light = 0x7f050086;
        public static final int wallet_hint_foreground_holo_dark = 0x7f050087;
        public static final int wallet_hint_foreground_holo_light = 0x7f050088;
        public static final int wallet_holo_blue_light = 0x7f050089;
        public static final int wallet_link_text_light = 0x7f05008a;
        public static final int wallet_primary_text_holo_light = 0x7f05008b;
        public static final int wallet_secondary_text_holo_dark = 0x7f05008c;
    }
    public static final class id {
        public static final int android_pay = 0x7f08001a;
        public static final int android_pay_dark = 0x7f08001b;
        public static final int android_pay_light = 0x7f08001c;
        public static final int android_pay_light_with_border = 0x7f08001d;
        public static final int book_now = 0x7f080023;
        public static final int buyButton = 0x7f08002a;
        public static final int buy_now = 0x7f08002b;
        public static final int buy_with = 0x7f08002c;
        public static final int buy_with_google = 0x7f08002d;
        public static final int classic = 0x7f080036;
        public static final int dark = 0x7f08003d;
        public static final int donate_with = 0x7f08004a;
        public static final int donate_with_google = 0x7f08004b;
        public static final int googleMaterial2 = 0x7f08005f;
        public static final int google_wallet_classic = 0x7f080060;
        public static final int google_wallet_grayscale = 0x7f080061;
        public static final int google_wallet_monochrome = 0x7f080062;
        public static final int grayscale = 0x7f080063;
        public static final int holo_dark = 0x7f080066;
        public static final int holo_light = 0x7f080067;
        public static final int light = 0x7f080077;
        public static final int logo_only = 0x7f08007d;
        public static final int match_parent = 0x7f080080;
        public static final int material = 0x7f080081;
        public static final int monochrome = 0x7f080085;
        public static final int none = 0x7f080089;
        public static final int production = 0x7f08009e;
        public static final int sandbox = 0x7f0800a6;
        public static final int selectionDetails = 0x7f0800b9;
        public static final int slide = 0x7f0800be;
        public static final int strict_sandbox = 0x7f0800cd;
        public static final int test = 0x7f0800d2;
        public static final int wrap_content = 0x7f0800eb;
    }
    public static final class layout {
        public static final int wallet_test_layout = 0x7f0a0045;
    }
    public static final class string {
        public static final int wallet_buy_button_place_holder = 0x7f0c0049;
    }
    public static final class style {
        public static final int WalletFragmentDefaultButtonTextAppearance = 0x7f0d0136;
        public static final int WalletFragmentDefaultDetailsHeaderTextAppearance = 0x7f0d0137;
        public static final int WalletFragmentDefaultDetailsTextAppearance = 0x7f0d0138;
        public static final int WalletFragmentDefaultStyle = 0x7f0d0139;
    }
    public static final class styleable {
        public static final int[] CustomWalletTheme = { 0x7f03008e, 0x7f0301c6, 0x7f0301de };
        public static final int CustomWalletTheme_customThemeStyle = 0;
        public static final int CustomWalletTheme_toolbarTextColorStyle = 1;
        public static final int CustomWalletTheme_windowTransitionStyle = 2;
        public static final int[] WalletFragmentOptions = { 0x7f03002d, 0x7f0300a0, 0x7f0300b8, 0x7f0300b9 };
        public static final int WalletFragmentOptions_appTheme = 0;
        public static final int WalletFragmentOptions_environment = 1;
        public static final int WalletFragmentOptions_fragmentMode = 2;
        public static final int WalletFragmentOptions_fragmentStyle = 3;
        public static final int[] WalletFragmentStyle = { 0x7f030052, 0x7f030053, 0x7f030054, 0x7f030055, 0x7f030126, 0x7f030127, 0x7f030128, 0x7f030129, 0x7f03012a, 0x7f03012b, 0x7f03012c };
        public static final int WalletFragmentStyle_buyButtonAppearance = 0;
        public static final int WalletFragmentStyle_buyButtonHeight = 1;
        public static final int WalletFragmentStyle_buyButtonText = 2;
        public static final int WalletFragmentStyle_buyButtonWidth = 3;
        public static final int WalletFragmentStyle_maskedWalletDetailsBackground = 4;
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 5;
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 6;
        public static final int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 7;
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 8;
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
        public static final int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 10;
    }
}
